//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMiniMart.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift_work
    {
        public string person_id { get; set; }
        public int shift_id { get; set; }
        public Nullable<bool> check_done { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Shift_detail Shift_detail { get; set; }
    }
}
